apiVersion: v1
kind: Service
metadata:
  name: api-producer-service
  namespace: tech-challenge
spec:
  selector:
    app: api-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
