version: '3.8'

services:
  api-producer:
    build:
      context: .
      dockerfile: Api.Producer/Dockerfile
    ports:
      - "5000:80"  # Mapeie as portas conforme necessário
    environment:
      - ASPNETCORE_ENVIRONMENT=Production


  worker-consumer:
    build:
      context: .
      dockerfile: Worker.Consumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
