version: '3.8'

services:
  api-producer:
    build:
      context: .
      dockerfile: TechChallengeGrupo66/Dockerfile
    ports:
      - "5000:80"  # Mapeie as portas conforme necessário
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  worker-consumer:
    build:
      context: ./Worker.Consumer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
