apiVersion: v1
kind: Service
metadata:
  name: api-producer-service
  namespace: tech-challenge
spec:
  selector:
    app: api-producer
  ports:
    - protocol: TCP
      port: 5000        # Porta dentro do container
      targetPort: 5000  # Porta do container
      nodePort: 30009   # Porta exposta no nó (escolha entre 30000-32767)
  type: NodePort
