apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-producer-ingress
  namespace: tech-challenge
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-producer-service
                port:
                  number: 5000
